### ISSUE TITLE
[Feature] Add Option to Remove Merge Commit 

### ISSUE THREAD

**Issue by Huzaifa-Asif** [tj-actions/eslint-changed-files#1474]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

If we add an option to remove the merge commit before the eslint changes in the config option it will be very good, as the merge commit pulls changes from the base branch and it is causing a lot of issues in our workflow as we didn't want to do that and sometimes because of this un-necessary features are pulled and cause issue during deployment. 

### Describe the solution you'd like?

The solution should be adding a boolean variable in GitHub action eslint config where we can turn this on and off.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @Huzaifa-Asif, the merge commits wouldn’t be coming from this action. Based on testing the reason you are seeing merge commits are as a result of the [checkout action](https://github.com/actions/checkout) merging the base branch and the pull request branch latest commit. 

See: https://github.com/actions/checkout/issues/881

A solution for this would be 

```yml
- uses: actions/checkout@v4
  with:
    ref: ${{ github.event.pull_request.head.sha }}
    fetch-depth: 0
```

Mentioned here: https://github.com/actions/checkout/blob/v3.0.2/README.md#user-content-checkout-pull-request-head-commit-instead-of-merge-commit
