### ISSUE TITLE
[BUG] breaks if file path contains parenthesis

### ISSUE THREAD

**Issue by flo-dao** [tj-actions/eslint-changed-files#1641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The action breaks if there are parenthesis in the file path

### To Reproduce

1. Create a file with parenthesis in the path
2. Run the action
3. It breaks

### What OS are you seeing the problem on?

all

### Expected behavior?

It should not break

### Relevant log output

```shell
files matching the pattern "apps/superadmin/app/\(protected\)/workspaces/[env]/[workspaceId]/features/WorkspaceFeatures.tsx" were found.
  Please check for typing mistakes in the pattern.
  
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @flo-dao, Since https://github.com/reviewdog/reviewdog/issues/1674 has been created, this one will be closed to avoid duplication. Thanks
