### ISSUE TITLE
[Feature] Fail the job on lint errors

### ISSUE THREAD

**Issue by clintonb** [tj-actions/eslint-changed-files#397]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I want to avoid committing new lint errors into my codebase.

### Describe the solution you'd like?

Fail the build/job if any lint errors are detected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@clintonb Thanks for reporting this issue and creating a fix, the change should be available in the latest release.
