### ISSUE TITLE
[Feature] Provide option to make reviewdog PR comments optional

### ISSUE THREAD

**Issue by peterKaleta** [tj-actions/eslint-changed-files#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I cannot find any arguments/config to block `reviewdog` from putting comments on the PR itself. My team is migrating big repo with a lot of eslint warnings, we end up with dozens on dozens comments per PR which decreases readability.  

### To Reproduce

n/a

### What OS are you seeing the problem on?

macos-latest or macos-10.15

### Expected behavior?

option to pass flag/config to avoid posting comments to PRs for every found error/warning

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@peterKaleta Sorry for the delay this should now be available in the latest [release](https://github.com/tj-actions/eslint-changed-files/releases)

**Comment by peterKaleta** [comment]
🙌
