### ISSUE TITLE
[BUG] .eslintignore dir/** pattern throws "file ignored..." warning and fails eslint check

### ISSUE THREAD

**Issue by peterKaleta** [tj-actions/eslint-changed-files#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

As with https://github.com/tj-actions/eslint-changed-files/issues/270 the eslint still fails when the file is ignored in .eslintignore with  `File ignored because of a matching ignore pattern. Use "--no-ignore" to override.`. Config is exactly like the one in README.md but with properly set `.eslintignore` and `.eslintrc`. The pattern I've added in `.eslintignore`:

```
directoryName/**
```

I'm using the newest version. 

### To Reproduce

- create `testDir/index.js` in repo
- set `.gitignore` to `testDir/**`
- setup basic workflow with copy of the config from readme.MD
- run, expect script failing with `File ignored because of a matching ignore pattern. Use "--no-ignore" to override.`

### What OS are you seeing the problem on?

macos-latest or macos-10.15

### Expected behavior?

- not failing on filled `File ignored because of a matching ignore pattern. Use "--no-ignore" to override.` warning on not filling the warning

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Based on this a possible solution would be to exclude all files listed in `.gitignore|.eslintignore` since the changed files logic doesn't currently account for this.

See:
- https://github.com/eslint/eslint/issues/5623#issuecomment-209789397
- https://youtrack.jetbrains.com/issue/WEB-27100
- https://stackoverflow.com/questions/37927772/how-to-silence-warnings-about-ignored-files-in-eslint

**Comment by jackton1** [comment]
@clintonb @peterKaleta This should be resolved in the latest release. Thanks

**Comment by radiodario** [comment]
We are still seeing this issue in our repo, using v21
