### ISSUE TITLE
[Feature] Add the ability to skip annotation comments on unchanged sections

### ISSUE THREAD

**Issue by Thatkookooguy** [tj-actions/eslint-changed-files#431]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I've implemented the github action in a project we're linting little by little. This means that each file we change, has a very large number of lint errors. It's hard to see what is actually relating to the changed lines themselves

### Describe the solution you'd like?

Having an optional parameter for the github action to skip comments in changed files that are not in changed lines

### Describe alternatives you've considered?

Currently, I'm just hiding all the annotation in GitHub to show only the reviewdog comments (which are relevant to the changed lines)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@Thatkookooguy Sorry for the delay this should now be available in the latest [release](https://github.com/tj-actions/eslint-changed-files/releases)

**Comment by Thatkookooguy** [comment]
This is great! Thank you! 🙏🏽 
Now we have a lot less comments unrelated to the changed lines.

But I do think that it might be better to also ignore those errors when reporting on the outcome. Now, there are no comments (since the changed code is linted and fine), but the unchanged code still counts as errors for the pipeline and the pipeline is marked as failed.

I can live with the current behavior tho if this is too big of a feature or you think it's not a good behavior.

I also don't mind trying to implement it if you prefer

**Comment by jackton1** [comment]
@Thatkookooguy can you include a sample log output of the error that’s reported ?

**Comment by Thatkookooguy** [comment]
Sure, I'll share it when I get home.

But I mean linter errors for lines that have not changed in files that do

I'll create a MRE and share it with you

**Comment by jackton1** [comment]
@Thatkookooguy any updates on this?
