### ISSUE TITLE
[BUG] No files matching the pattern

### ISSUE THREAD

**Issue by 1337MARCEL** [tj-actions/eslint-changed-files#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

We have a code base with a file hierarchy that goes up to 4 levels. Using your action we're encountering the `No files matching the pattern` error on workflow run.

### To Reproduce

I created a [repository](https://github.com/1337MARCEL/eslint-changed-files-repo/tree/add-lint-workflow) for you that you can use to reproduce and hopefully resolve the issue. You can find the failed workflow run [here](https://github.com/1337MARCEL/eslint-changed-files-repo/runs/5488170573?check_suite_focus=true).

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I expect that the action works no matter how large & deep the code base goes.

### Relevant log output

```shell
eslint-changed-files
  
  Oops! Something went wrong! :(
  
  ESLint: 8.10.0
  
  No files matching the pattern "pages/api/hello.mjs pages/index.jsx" were found.
  Please check for typing mistakes in the pattern.
  
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337MARCEL** [comment]
Thanks for the quick fix! 🚀

**Comment by jackton1** [comment]
No worries
